name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and package Java app
      run:  mvn clean package
    - name: Build Docker image
      run: docker build . -t kuja921/hw1:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image to Docker Hub
      run: docker push kuja921/hw1:latest
    - name: Set up SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Set env
      run: |
        echo "GITHUB_ACTION_PATH=" >> $GITHUB_ENV

    - name: Deploy to server
      run: |
        docker ps
        docker stop kuja921hw1 || true
        docker rm kuja921hw1 || true
        docker pull kuja921/hw1:latest
        docker run -d -p 8080:8080 --name kuja921hw1 --restart always -v /var/run/docker.sock:/var/run/docker.sock -v kuja921test1v2_data:/data -v /etc/letsencrypt/live/kuja-portainer.freemyip.com:/certs/live/kuja-portainer.freemyip.com:ro -v /etc/letsencrypt/archive/kuja-portainer.freemyip.com:/certs/archive/kuja-portainer.freemyip.com:ro kuja921/hw1:latest --sslcert /certs/live/kuja-portainer.freemyip.com/fullchain.pem --sslkey /certs/live/kuja-portainer.freemyip.com/privkey.pem
